# import json
from fastapi import FastAPI, File, UploadFile

# Across Field
from starlette.middleware.cors import CORSMiddleware
# from typing import Optional
from pydantic import BaseModel

# Python WEB接口开发 Flask -> FastAPI
import modules.datasets as ds
import modules.models as md
import modules.statistic as st
import modules.utils as ut
import logging
import time
import os
# Add WEBAPP
app = FastAPI()

# Allow all
origins = ['*']

# Solver
app.add_middleware(CORSMiddleware,
                   allow_origins=origins,
                   allow_credentials=True,
                   allow_methods=['*'],
                   allow_headers=['*'])
# Set Logger
logging.basicConfig(filename='runtime.log', level=logging.INFO)


@app.get('/')
def homepage():
    logging.info("[Received Request]@/")
    return '''Welcome to SPR-Project.
    The backend is running now. Please goto <your-api-domain>/docs for documentation generated by Swagger UI.
    A usually local domain should be like: http://127.0.0.1/docs .'''


@app.get('/test')
def test():
    logging.info("[Received Request]@/test")
    try:
        return {'message': 'Test FastAPI successfully.'}
    except Exception as e:
        logging.error("[Disconnected]请检查链接及跨域问题。", str(e))


# Static Done
@app.get('/datasets/column/target')
def getRawTarget():
    logging.info("[Received Request]@/datasets/column/target")
    try:
        return {'message': 'Success, 成功获取', 'result': ds.getColumn('G')}
    except Exception as e:
        logging.error("[UnKnown]不能获取G列的未知错误，请检查链接。", str(e))


# Static Done
@app.get('/datasets/column/{col}')
def getRawColumn(col: str):
    logging.info("[Received Request]@/datasets/column/{}".format(col))
    return {'message': 'Success, 成功获取', 'result': ds.getColumn(col)}


@app.get('/model/{modelType}')
def getModel(modelType: str):
    logging.info("[Received Request]@/model/{}".format(modelType))
    return {'message': 'Success, 成功获取', 'result': st.modelStat[modelType]}


# Form Package
class attributes(BaseModel):
    School: str
    Class: int
    Age: int
    Address: str
    Famsize: str
    Pstatus: str
    Medu: int
    Fedu: int
    Mjob: str
    Fjob: str
    Reason: str
    Guardian: str
    TravelTime: int
    StudyTime: int
    Failures: int
    SchoolSup: bool
    FamSup: bool
    Paid: bool
    Activities: bool
    Nursery: bool
    Higher: bool
    Internet: bool
    Romantic: bool
    FamRel: int
    FreeTime: int
    GoOut: int
    Dalc: int
    Walc: int
    Health: int
    Absences: int
    # G: int


# Static Done
@app.get('/stat/importance')
def getImportance():
    logging.info("[Received Request]@/stat/importance")
    return {'message': 'Success, 成功获取', 'result': st.importance}


# Static Done
@app.get('/stat/appearance')
def getAppearance():
    logging.info("[Received Request]@/stat/appearance")
    return {'message': 'Success, 成功获取', 'result': st.appearance}


@app.post('/predict/form')
def getPredict(form: attributes):
    logging.info("[Received Request]@/predict/form")
    return {'message': 'Success, 成功获取', 'result': md.predictForm(form)}


@app.post('/predict/dataset')
async def getPredictSet(dataset: UploadFile = File(...)):
    logging.info("[Received Request]@/predict/dataset")
    start = time.time()
    try:
        res = await dataset.read()
        with open(os.path.join(ut.getDatasetsFullPath(dataset.filename)),
                  "wb") as f:
            f.write(res)
        r = md.predictFile(ut.getDatasetsFullPath(dataset.filename))
        #print(r)
        return {
            "message": "Success, 成功获取",
            'time': time.time() - start,
            'filename': dataset.filename,
            'result': r
        }
    except Exception as e:
        #print(str(e))
        return {
            "message": str(e),
            'time': time.time() - start,
            'filename': dataset.filename
        }
